### PR TITLE
Fix #37, don't delete options on first client

### LINKED ISSUE #37: stomp+ssl failover not working?
I have the following connection string:
`failover:(stomp+ssl://host1:61614,stomp+ssl://host2:61614)?transport.timeout=5000`

I'm also passing the `ssl:` option in the `OnStomp::Client` constructor, with a path to a CA cert bundle.

`host2` is our currently active broker, and `host1` is currently unreachable.

The onstomp connection never seems to establish (seems to hang). I am seeing an error in our `host2` broker logs that indicates the SSL handshake is failing ("unknown_ca").

I'm wondering if the failover client isn't specifying the ssl CA cert option on the failover? I see #26 was filed, but I'm not sure if this is the same issue?

If I switch the order of hosts in my connection string (host2, then host1), it connects and works as expected.

Unfortunately this is production-impacting for us at the moment, so I'm hoping you might have some ideas?

### PR DESCRIPTION
**Pull request by l8nite**
Fixes #37

### CODE REVIEW

File: lib/onstomp/client.rb [hunk 1]
```diff
@@ -9,7 +9,7 @@ class OnStomp::Client
   include OnStomp::Interfaces::ReceiptManager
   include OnStomp::Interfaces::SubscriptionManager
   include OnStomp::Components::Scopes
-  
+
```
Comment (l8nite) [inline lib/onstomp/client.rb]: Bah, sorry - I guess my editor stripped out the trailing whitespace all over this file.

Comment (iande) [reply lib/onstomp/client.rb]: No problem, it could use the cleanup!
